# ç½‘ç«™çš„åŸºæœ¬ä¿¡æ¯
site:
  tab: Frosti # æµè§ˆå™¨æ ‡ç­¾æ ä¸Šæ˜¾ç¤ºçš„æ–‡æœ¬
  title: ğŸ’  Jursin çš„ Blog # ç½‘ç«™çš„æ ‡é¢˜
  description: ä¸€ä¸ªä½¿ç”¨ Frosti ä¸»é¢˜çš„åšå®¢ ğŸš€ ç”± Astro é©±åŠ¨
  language: zh
  favicon: /favicon.ico # ç½‘ç«™çš„å›¾æ ‡ï¼Œç”¨äºæµè§ˆå™¨æ ‡ç­¾æ å’Œå…¶ä»–åœ°æ–¹æ˜¾ç¤º
  theme: # æ›´å¤šä¸»é¢˜ https://daisyui.com/docs/themes/
    light: winter # ä¸»é¢˜çš„æµ…è‰²æ¨¡å¼
    dark: dracula # ä¸»é¢˜çš„æ·±è‰²æ¨¡å¼
    code: github-dark # ä»£ç å—çš„ä¸»é¢˜ https://shiki.style/themes
  date_format: YYYYå¹´MMæœˆDDæ—¥ # æ—¥æœŸæ ¼å¼è®¾ç½®ï¼Œæ”¯æŒè‡ªå®šä¹‰æ ¼å¼
  blog: # åšå®¢ç›¸å…³é…ç½®
    pageSize: 8 # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡
  menu: # èœå•é…ç½®
    - id: home # èœå•é¡¹çš„å”¯ä¸€æ ‡è¯†ç¬¦
      text: ä¸»é¡µ # èœå•é¡¹æ˜¾ç¤ºçš„æ–‡æœ¬
      href: / # èœå•é¡¹é“¾æ¥çš„åœ°å€
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: å…³äº
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: åšå®¢
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: å…¨éƒ¨åšå®¢
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: documentation
          text: æ–‡æ¡£
          href: /blog/category/æ–‡æ¡£
          svg: "material-symbols:unknown-document-outline-rounded"
          target: _self
        - id: examples
          text: ç¤ºä¾‹
          href: /blog/category/ç¤ºä¾‹
          svg: "material-symbols:deployed-code-outline"
          target: _self
        # å­èœå•é¡¹é…ç½®
    - id: project
      text: é¡¹ç›®
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: æœ‹å‹
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self

# ç”¨æˆ·çš„ä¸ªäººä¿¡æ¯
user:
  name: Jursin # ç”¨æˆ·å
  site: "https://blog.jursin.top" # ç”¨æˆ·çš„ç½‘ç«™é“¾æ¥
  avatar: /profile.png # ç”¨æˆ·å¤´åƒè·¯å¾„
  sidebar: # ä¾§è¾¹æ é…ç½®
    social:
      - href: "https://github.com/Jursin"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/1575907920"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://www.douyin.com/user/MS4wLjABAAAAQGQcpmhfTWT-dnMkBX1Dtdw4mqk-WUPiz1Stbb5nn7Q"
        ariaLabel: Douyin
        title: Douyin
        svg: "ri:tiktok-line"
  footer:
    social:
      - href: "https://github.com/Jursin"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/1575907920"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://www.douyin.com/user/MS4wLjABAAAAQGQcpmhfTWT-dnMkBX1Dtdw4mqk-WUPiz1Stbb5nn7Q"
        ariaLabel: Douyin
        title: Douyin
        svg: "ri:tiktok-line"
